server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: enrollment-service
              uri: lb://enrollment-service
              predicates:
                - Path=/enrollment-service/**
              filters:
                - StripPrefix=1